'use strict';

const { RUNTIME_PROCESS_EXIT_CODES } = require('../shared/automation-runtime-contract');

const EXIT_CODES = Object.freeze({
  SUCCESS: 0,
  USAGE: 2,
  RUNTIME_UNAVAILABLE: RUNTIME_PROCESS_EXIT_CODES.PROFILE_INITIALIZATION_FAILED,
  PROFILE_LOCKED: RUNTIME_PROCESS_EXIT_CODES.PROFILE_LOCKED,
  AUTH_FAILED: 12,
  PROTOCOL_MISMATCH: 13,
  COMMAND_FAILED: 20,
  INTERNAL: 70,
});

module.exports = { EXIT_CODES };
